name: CI

on:
  push:
    branches: [ main, "release/**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - run: go mod download

      # unit-tests
      - run: go test -short -v -coverprofile=cover.out

      # build binary
      - run: go build -o main

      # demo + harness
      - run: go run . demo
      - run: go run . eval
      - run: go run . taskeval
      - run: go run . bencheval
      - run: go run . needle

      # coverage
      - run: go tool cover -func=cover.out | grep total
